- name: Provisioning EC2 instance
  hosts: localhost
  connection: local
  gather_facts: False
  tags: provisioning

  vars:
    instance_type: t2.micro
    security_group: prod_build_nodes
    image: ami-0d2751e39abf67ea8
    region: us-east-2
    keypair: MKey1
    count: 2
    hostname1: build_node
    hostname2: prod_node
    ec2_access_key: AKIAWMREQVX2P4477PAB
    ec2_secret_key: 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

  tasks: 

    - name: Create new security group
      module: ec2_group
      name: "{{ security_group }}"
      description: Security Group for new instance
      region: "{{ region }}"
      rules:
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: 0.0.0.0/0
      rules_egress:
      - proto: all
        cidr_ip: 0.0.0.0/0

    - name: Launch new EC2 instance
        ec2:
          group={{ security_group }}   
          instance_type={{ instance_type }} 
          ws_access_key={{ ec2_access_key }}
          aws_secret_key={{ ec2_secret_key }}
          image={{ image }}  
          wait=true
          region={{ region }}
          keypair={{ keypair }}
          count={{ count }}
       register: ec2_info              

    
