- name: Provisioning EC2 instance
  hosts: localhost
  connection: local
  gather_facts: False
  tags: provisioning

  vars:
    ansible_python_interpreter: /usr/bin/python3
    instance_type: t2.micro
    security_group: prod_build_nodes
    image: ami-0d2751e39abf67ea8
    region: us-east-2
    keypair: MKey1
    count: 1
    hostname1: build_node
    hostname2: prod_node
 
  tasks: 

    - name: Create new security group
      local_action:
        module: ec2_group
        name: "{{ security_group }}"
        description: Security Group for new instance
        region: "{{ region }}"
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0   
        rules_egress:
          - proto: all
            cidr_ip: 0.0.0.0/0

    
    - name: Launch new EC2 instance
      ec2:	
        group: "{{ security_group }}"           
        instance_type : "{{ instance_type }}"       
        image: "{{ image }}"
        wait: true
        region: "{{ region }}"     
        keypair: "{{ keypair }}"
        count: "{{ count }}"
      register: result_ec2_instance                           

    
